if [[ -f $HOME/.github_token ]]
then
  export GITHUB_TOKEN=$(cat $HOME/.github_token)
fi

export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH="$PATH:`yarn global bin`"

OB_PATH_WORKSPACE="$HOME/Projects"

if [ -f ~/.zsh_aliases ]; then
    . ~/.zsh_aliases
fi
